server:
  port: 80
spring:
  application:
    name: atguigu-crowd-zuul
  redis:
    host: 192.168.47.131
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    crowd-portal:
      service-id: atguigu-crowd-auth
      path: /**
    crowd-project:
      service-id: atguigu-crowd-project
      path: /project/**
  add-host-header: true
