server:
  port: 4000
spring:
  redis:
    host: 192.168.47.130
  session:
    store-type: redis
  application:
    name: atguigu-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka